String characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

enum WordKey { technology, animals, countries, foods, professions }

Map<WordKey, List<String>> wordsList = {
  WordKey.technology: [
    'mouse',
    'keyboard',
    'email',
    'phone',
    'browser',
    'software',
    'password',
    'database',
    'bluetooth',
    'firewall',
    'robotics',
    'nanotechnology',
    'biometrics',
    'encryption',
    'algorithm'
  ],
  WordKey.animals: [
    'cat',
    'dog',
    'bird',
    'fish',
    'bear',
    'elephant',
    'dolphin',
    'kangaroo',
    'penguin',
    'turtle',
    'platypus',
    'komodo',
    'chameleon',
    'porcupine',
    'ostrich'
  ],
  WordKey.countries: [
    'usa',
    'uk',
    'china',
    'india',
    'brazil',
    'australia',
    'mexico',
    'canada',
    'italy',
    'spain',
    'japan',
    'russia',
    'germany',
    'vietnam',
    'argentina'
  ],
  WordKey.foods: [
    'pizza',
    'apple',
    'cake',
    'bread',
    'banana',
    'avocado',
    'sushi',
    'pancake',
    'pineapple',
    'burrito',
    'quinoa',
    'kimchi',
    'durian',
    'escargot',
    'artichoke',
  ],
  WordKey.professions: [
    'doctor',
    'teacher',
    'nurse',
    'chef',
    'driver',
    'architect',
    'electrician',
    'pharmacist',
    'journalist',
    'librarian',
    'paleontologist',
    'astronomer',
    'geneticist',
    'geologist',
    'economist'
  ],
};

List<String> typeList = [
  'Technology',
  'Animals',
  'Countries',
  'Foods',
  'Professions',
];
